# Generated by Django 3.0 on 2021-04-29 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Категории')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=255, verbose_name='Размер')),
                ('count', models.IntegerField(verbose_name='Количество в пачке')),
            ],
            options={
                'verbose_name': 'Размер',
                'verbose_name_plural': 'Размеры',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True, verbose_name='Название акции')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media', verbose_name='Изображение 1200х300')),
                ('available', models.BooleanField(default=True, verbose_name='Актуальность акции')),
            ],
            options={
                'verbose_name': 'Акция',
                'verbose_name_plural': 'Акции',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=50, verbose_name='Наименование')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media', verbose_name='Изображение')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='media', verbose_name='Изображение')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='media', verbose_name='Изображение')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='media', verbose_name='Изображение')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='media', verbose_name='Изображение')),
                ('image6', models.ImageField(blank=True, null=True, upload_to='media', verbose_name='Изображение')),
                ('image7', models.ImageField(blank=True, null=True, upload_to='media', verbose_name='Изображение')),
                ('image8', models.ImageField(blank=True, null=True, upload_to='media', verbose_name='Изображение')),
                ('image9', models.ImageField(blank=True, null=True, upload_to='media', verbose_name='Изображение')),
                ('image10', models.ImageField(blank=True, null=True, upload_to='media', verbose_name='Изображение')),
                ('discription', models.TextField(null=True, verbose_name='Описание')),
                ('color', models.CharField(max_length=200, null=True, verbose_name='цвет')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('available', models.BooleanField(default=True, verbose_name='Наличие товара')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sonun.Category', verbose_name='Категория')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sonun.Size', verbose_name='Размер')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ('title',),
            },
        ),
    ]
