# Generated by Django 3.0 on 2021-05-01 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sonun', '0003_auto_20210501_1815'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=300, verbose_name='Цвет')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.AlterField(
            model_name='size',
            name='size',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Размер'),
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.ManyToManyField(max_length=200, null=True, to='sonun.Color', verbose_name='цвет'),
        ),
    ]
