# Generated by Django 3.0 on 2021-05-02 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sonun', '0005_auto_20210501_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='category', to='sonun.Category', verbose_name='Категория'),
        ),
    ]
